name: ci-dev-pipeline
on:
  push:
    branches:
      - 'main'
env:
  BASE_DIR: /pkg
  IMAGE_NAME: cno-api
  VERSION_IMAGE: v2.0.0
  ORGANIZATION_NAME: beopenit
  IMAGE_NAME_TAG: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
        env: 
          IMAGE_NAME_TAG: "${{env.ORGANIZATION_NAME}}/${{env.IMAGE_NAME}}:${{env.VERSION_IMAGE}}-${{steps.commit.outputs.short}}-${{steps.date.outputs.date}}"
      - name: Test
        run: | 
          echo "$IMAGE_NAME_TAG"
